#!/usr/bin/env python3
"""
regenerate_index.py — Deterministic index.md builder for brightops-wiki.

Walks <wiki_root>/docs/wiki/pages/**/*.md, groups by top-level project subdir,
and emits a new docs/wiki/index.md that wiki_check.py's substring match (at
line 110 of the Ss1024sS bootstrap's wiki_check template) is guaranteed to
find.

This is the CRITICAL piece that lets the single-project Ss1024sS bootstrap
tolerate our multi-project layout: wiki_check looks for each page's relative
path as a substring in index.md, and this script guarantees each path appears
verbatim.

Required wiki root files (README, SCHEMA, log, project-overview,
current-status, sources-and-data, github-and-raw-strategy) are preserved at
the top of the index; topic pages are grouped under "## Project: <slug>".

Run as the FIRST step of /wiki-process-inbox, before wiki_check.py.

The wiki location is read from BRIGHTOPS_WIKI_ROOT env var, or via the
--wiki-root CLI argument. Default is $HOME/Documents/wiki.
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Required files that live at wiki root (not under pages/) and should appear
# first in the index. Order is preserved as listed.
REQUIRED_ROOT_FILES = [
    ("README.md", "wiki readme"),
    ("SCHEMA.md", "frontmatter and provenance schema"),
    ("project-overview.md", "what this wiki is and what it covers"),
    ("current-status.md", "cross-project status snapshot"),
    ("sources-and-data.md", "where raw research lives"),
    ("github-and-raw-strategy.md", "git vs raw split and rationale"),
]


def read_title(page: Path) -> str:
    """Extract the 'title:' value from YAML frontmatter, or fall back to stem."""
    try:
        text = page.read_text(encoding="utf-8")
    except Exception:
        return page.stem
    if not text.startswith("---"):
        return page.stem
    end = text.find("\n---", 4)
    if end < 0:
        return page.stem
    for line in text[4:end].splitlines():
        if ":" in line:
            k, _, v = line.partition(":")
            if k.strip() == "title":
                return v.strip().strip('"').strip("'")
    return page.stem


def resolve_wiki_root(cli_arg: str | None) -> Path:
    """CLI arg → env var → default."""
    if cli_arg:
        return Path(cli_arg).expanduser().resolve()
    env = os.environ.get("BRIGHTOPS_WIKI_ROOT")
    if env:
        return Path(env).expanduser().resolve()
    return (Path.home() / "Documents" / "wiki").resolve()


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate the wiki index.md from pages/**")
    parser.add_argument(
        "--wiki-root",
        help="Path to the wiki root (default: $BRIGHTOPS_WIKI_ROOT or $HOME/Documents/wiki)",
    )
    args = parser.parse_args()

    wiki_project_root = resolve_wiki_root(args.wiki_root)
    wiki_dir = wiki_project_root / "docs" / "wiki"
    pages_dir = wiki_dir / "pages"
    index_path = wiki_dir / "index.md"

    if not wiki_dir.exists():
        print(f"regenerate_index: wiki dir does not exist: {wiki_dir}", file=sys.stderr)
        return 1

    out: list[str] = []
    out.append("# Wiki Index")
    out.append("")
    out.append("<!-- AUTO-GENERATED by brightops-wiki regenerate_index.py — do not hand-edit. -->")
    out.append("<!-- Manual organizational notes belong in project-overview.md instead. -->")
    out.append("")
    out.append("## Wiki meta")
    out.append("")
    for filename, description in REQUIRED_ROOT_FILES:
        if (wiki_dir / filename).exists():
            out.append(f"- [{filename}](./{filename}) — {description}")
    out.append("")

    if pages_dir.exists():
        projects = sorted(p for p in pages_dir.iterdir() if p.is_dir() and not p.name.startswith("."))
        for project_dir in projects:
            pages = sorted(project_dir.rglob("*.md"))
            if not pages:
                continue
            out.append(f"## Project: {project_dir.name}")
            out.append("")
            for page in pages:
                rel = page.relative_to(wiki_dir).as_posix()
                title = read_title(page)
                out.append(f"- [{title}](./{rel}) — `{rel}`")
            out.append("")

    out.append("## Activity")
    out.append("")
    out.append("- [log.md](./log.md) — append-only activity log")
    out.append("")

    index_path.write_text("\n".join(out), encoding="utf-8")

    page_count = sum(1 for _ in pages_dir.rglob("*.md")) if pages_dir.exists() else 0
    print(f"regenerate_index: wrote {index_path} "
          f"({len(REQUIRED_ROOT_FILES)} required + {page_count} topic pages)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
